name: layout
description: >-
  Sample app from "Building Layouts", https://docs.flutter.dev/ui/layout.
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg